### ISSUE TITLE
Why the rpc call encointerBazaar.businessRegistry requires an account Id?

### ISSUE THREAD

**Issue by anizeani** [encointer/encointer-node#105]
Doesn't it make more sense to list all businesses per community? Why would the call require an account? 
If it should list only the businesses in the community by the specific account, how about listing all businesses for the whole community?

**Comment by clangenb** [comment]
This is not something we can influence. It's simply the default generated rpc for our storage model of the pallet. This is exactly why we introduced the custom rpc `bazaar.getBusinesses`, which only requires a `CommunityId`
