### ISSUE TITLE
bazaar rpc methods don't work

### ISSUE THREAD

**Issue by anizeani** [encointer/encointer-node#106]
can't see bazaar methods in polkadot-js.org/apps
I see the bazaar methods in the returned list when calling the pallet "rpc" and method "methods", but I can not see them in the dropdown in polkadot-js, nor can I call them in javascript:

example: 
 ```console
  const rpc = await api.rpc.rpc.methods((methods) => {
    console.log(methods);
    });
  ```
  returns all rpc methods: 
  ```console
      author_hasKey,
      author_hasSessionKeys,
      author_insertKey
      ...
      bazaar_getBusinesses,
      bazaar_getOfferings,
      bazaar_getOfferingsForBusiness,
      ...
  ```
now, I want to try to call such a method:
```console
const unsub = await api.rpc.author.pendingExtrinsics((extrinsics) => {
  console.log(extrinsics);
});
```
this works.
```console
haskey = await api.rpc.author.hasKey( (value) => {
  console.log(value);
});    
```
this will return an error, that the function hasKey requires an argument, but the function is recognized.

The following call will return undefined, because it doesnt find the method getBusinesses: 
```console
const gb = await api.rpc.bazaar.getBusinesses((businesses) => {
  console.log(businesses)
});
```
Maybe this is a solution: 
https://polkadot.js.org/docs/api/start/rpc.custom/
there it is shown, how custom methods are defined: 
for example: 
```console
const api = await ApiPromise.create({
  rpc: {
    firstModule: {
      testMethod: {
        description: 'Just a test method',
        params: [
          {
            name: 'index',
            type: 'u64'
          },
          {
            name: 'at',
            type: 'Hash',
            isOptional: true
          }
        ],
        type: 'Balance'
      },
      anotherMethod: { ... },
      ...
    },
    anotherModule: { ... },
    ...
  },
  ...
});
```
Then, a custom rpc call should be callable by the command: api.rpc.firstModule.testMethod(...)
Is this maybe what needs to be done to access custom rpc methods?

**Comment by clangenb** [comment]
1. You will never see the custom rpc's in the bazaar- pallet's dropdown. Those are only the standard derived calls that access storage value directly. Neither the node nor polkadot-js has any means to know that these calls belong to the bazaar pallet. Or is it missing in the rpc-section's dropdown?

2. I thought this is not necessary to explicitly add custom rpc's to the API, but then you might need to call the method via the `api.derive` interface. However, we did it for the communities pallet: 
https://github.com/encointer/encointer-js/blob/master/packages/types/src/interfaces/community/definitions.ts
 
So we should probably do that for the bazaar pallet also, here:

https://github.com/encointer/encointer-js/blob/master/packages/types/src/interfaces/bazaar/definitions.ts

@anizeani can you make an issue for than in encointer-js and implement that?

**Comment by anizeani** [comment]
> 1. You will never see the custom rpc's in the bazaar- pallet's dropdown. Those are only the standard derived calls that access storage value directly. Neither the node nor polkadot-js has any means to know that these calls belong to the bazaar pallet. Or is it missing in the rpc-section's dropdown?

<h2>They are all missing in the dropdowns rpc-section (also community_getAll).</h2> 

> 2. I thought this is not necessary to explicitly add custom rpc's to the API, but then you might need to call the method via the `api.derive` interface. However, we did it for the communities pallet:
>    https://github.com/encointer/encointer-js/blob/master/packages/types/src/interfaces/community/definitions.ts
>    
> So we should probably do that for the bazaar pallet also, here:
> 
> https://github.com/encointer/encointer-js/blob/master/packages/types/src/interfaces/bazaar/definitions.ts
> 
> @anizeani can you make an issue for than in encointer-js and implement that?
<h2>yes, I will first figure out, if it is really necessary.</h2>

**Comment by anizeani** [comment]
This issue is not resolved, but I guess we can close it summarizing that those custom rpc methods will not appear in the polkodat-js app?
