### ISSUE TITLE
make bot-community.py script generic to be used standalone

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-node#108]
To maintain constantly active bot communities, we should simplify the usage of bot-communities

currently, the following things are hard-coded:
* cli binary location
* test_data location
* client wrapper in workdir

Also
* [x] allow usage without IPFS. just skip this stuff if there's any error. don't abort
* [x] remove `#` in front of community name

**Comment by brenzi** [comment]
in addition to the things discussed @anizeani

**Comment by brenzi** [comment]
Test data should not be in the root folder, but below `client`

**Comment by anizeani** [comment]
@brenzi test-data are moved with PR #126

**Comment by anizeani** [comment]
> To maintain constantly active bot communities, we should simplify the usage of bot-communities
> 
> currently, the following things are hard-coded:
> 
> * cli binary location
> * test_data location
> * client wrapper in workdir
> 
> Also
> 
> * [x]  allow usage without IPFS. just skip this stuff if there's any error. don't abort
> * [x]  remove `#` in front of community name

@brenzi what do you recommend? to manually enter binary location?

**Comment by brenzi** [comment]
The best longterm solution would be an env variable IMO.
```
export ENCOINTER_CLIENT="./encointer-client-notee"
```
The derivation priority should be (and I really don't think we will use the `-client-notee` suffix much longer):
1. env ENCOINTER_CLIENT
2. /usr/local/bin/encointer
3. /usr/bin/encointer

**Comment by anizeani** [comment]
test data location fixed with #126
encointer exported as ENCOINTER_CLIENT and used in code #126 (didnt unterstand your comment about priority with 2. /usr/local/... and 3.)
what about "client wrapper in workdir"? what did you mean with that?

**Comment by brenzi** [comment]
let's close it for now. we can improve this when needed
