### ISSUE TITLE
benchmark script stuck in infinity loop

### ISSUE THREAD

**Issue by anizeani** [encointer/encointer-node#121]
since commit [c3caf6e8e92a2db448f40079e62f996e6d886793](https://github.com/encointer/encointer-node/commit/c3caf6e8e92a2db448f40079e62f996e6d886793)
running ./bot-community.py benchmark is stuck in the same phase. 
how is the phase supposed to change?

**Comment by brenzi** [comment]
you need to run ./phase.py which changes the phase after a few empty blocks

**Comment by anizeani** [comment]
Good, I will add this to the readme👍
