### ISSUE TITLE
deploy testnet cantillon nodes

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-node#16]
Deploy a testnet similar to testnet gesell, but with the `sgx-master` branch, leveraging SubstraTEE

# Steps for testnet Gesell
Three droplets on digitalocean:

Validators
* gesell01.encointer.org
* gesell02.encointer.org

API node (for RPC and WS)
* gesell.encointer.org

setup 
  passwd
  adduser gesell
  usermod -aG sudo gesell
  su gesell
  mkdir ~/.ssh
  # add ssh keys to authorized_keys
  wget https://github.com/encointer/encointer-node/releases/download/v0.2.0/encointer-node
firewall
  sudo ufw allow OpenSSH
  sudo ufw allow 9944
  sudo ufw allow 30333
  sudo ufw enable
  
systemd service along: https://wiki.polkadot.network/docs/en/maintain-guides-how-to-systemd
watch node logs:
  sudo journalctl -f -u encointer-testnet-gesell-validator

Setup ChainSpec and Key provisioning along substrate tutorial:
https://www.substrate.io/tutorials/start-a-private-network/v2.0.0-alpha.8

Store all mnemonics and keys in our passwordsafe. not on the nodes!

secure websocket full api-node (non-validator) with letsencrypt
follow https://wiki.polkadot.network/docs/en/maintain-wss#domain-and-certbot
  sudo ufw allow 443/tcp
  sudo add-apt-repository ppa:certbot/certbot
  sudo apt-get install python-certbot-nginx
  sudo ufw allow 'Nginx Full'
then start a full node there with 
  ./encointer-node   --base-path /home/gesell/chain --chain gesellSpecRaw.json --port 30333 --ws-port 9944 --rpc-cors all --rpc-po 9933  --name gesell-api

**Comment by electronix** [comment]
Validators and API:
* Cantillon-validator-01: 161.35.76.124 (cantillon01.encointer.org)
* Cantillon-validator-02: 167.172.178.106 (cantillon02.encointer.org)
* Cantillon-api: 134.122.93.143 (wss://cantillon.encointer.org)
