### ISSUE TITLE
register-businesses uploading only folders, should also upoad single files

### ISSUE THREAD

**Issue by anizeani** [encointer/encointer-node#169]
since pr #145, we upload everything to ipfs with a folder, even single files.
The bazaar-web was implemented to read files (images of businesses or offerings and description jsons).
The register-businesses.py script was originally also just uploading files and not folders. 
since #145, this broke the functionality of the script and the web-ui.
In any case, I think it makes sense to have the possibility to upload folders OR files for simplicity of the other side which has to fetch the data. 
Therefore I would suggest to extend the ipfs client with single file upload methods:  #168

**Comment by clangenb** [comment]
* I guess this has been solved with #168 ?
