### ISSUE TITLE
[bazaar] implement final business/offering data models and helper scripts

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-node#171]
Implement full json formats in client examples and offer helper script to register a custom business or offering manually taking json as input

Business: https://schema.org/LocalBusiness
* assume geolocation will always be supplied (but it is in fact optional)

Offering:
* only offer, not demand: https://schema.org/Offer
* https://schema.org/Product

More info on the data model
https://github.com/encointer/pallets/blob/master/bazaar/README.md

helper script 
```
bazaar.py register-business <cid> <bizaccount> LocalBusiness.json
bazaar.py register-offering <cid> <bizaccount> --price <amount> Product.json
```

**Comment by anizeani** [comment]
accoring to the scheme, the business or offering already contains a property called logo. i guess it should be an ipfs cid of the logo. 
but the user didn't upload yet an image. 
so how does one get the cid for it? 
do we provide a script, that just uploads a single file to our ipfs node?

**Comment by anizeani** [comment]
according to the scheme, the business or offering already contains a property called logo. i guess it should be an ipfs cid of the logo.
but the user didn't upload yet an image.
so how does one get the cid for it?
do we provide a script, that just uploads a single file to our ipfs node?

**Comment by anizeani** [comment]
can I expect, that bizaccount is already a created/fauceted account on the chain of the specific cid?

**Comment by anizeani** [comment]
how should one create a bizaccount?

**Comment by anizeani** [comment]
according to the scheme https://github.com/encointer/pallets/blob/master/bazaar/README.md,
how are the offerings tracked in the localBusiness.json ? 
shouldn't there be a property which stores all the cid's of the offerings of the business?

**Comment by brenzi** [comment]
> shouldn't there be a property which stores all the cid's of the offerings of the business?

No. 
that's all stored in our onchain registry. plz check our rpc method `bazaar_getOfferingsForBusiness`

**Comment by brenzi** [comment]
> how should one create a bizaccount?

I don't get this question. a biz account is an account like any other - and later it will be a proxied account, but don't worry about this now

> can I expect, that bizaccount is already a created/fauceted account on the chain of the specific cid?

For now, assume the bizaccount is just one of the bot-community participants. Or just create a new one if that's easier and feed it from the faucet

**Comment by anizeani** [comment]
> > how should one create a bizaccount?
> 
> I don't get this question. a biz account is an account like any other - and later it will be a proxied account, but don't worry about this now
> 
> > can I expect, that bizaccount is already a created/fauceted account on the chain of the specific cid?
> 
> For now, assume the bizaccount is just one of the bot-community participants. Or just create a new one if that's easier and feed it from the faucet

My question is related to the flow of biz creation: 
Should one run the script and during this script create an account, faucet it and then create a biz
Or
The user already did somehow create an account (i.e. through the app) and just needs to enter the account address to register a biz in his name
