### ISSUE TITLE
register EDI businesses and offerings

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-node#172]
* Business: Küche Pauli
   * Offering: Kaffee ( 2.7183 EDI)
* Küche Edison
   * Offering: Kaffee ( 2.7183 EDI)
* Weidlibräu
   * Offering: Bier (3.1416 EDI)

community: `u0qj94fxxJ6`

long/lat from https://raw.githubusercontent.com/encointer/encointer-node/master/client/test-data/test-locations-scs.json

* [x] generate json files for LocalBusiness.json and Product.json (test-data folder)
* [x] resolve #171
* [x] register these on testnet gesell

**Comment by brenzi** [comment]
promo images for businesses:

Küche Pauli
![image](https://user-images.githubusercontent.com/10366175/155381825-57a4b2fa-3f19-4546-b608-161d9dc48dad.png)

Weidlibräu
![image](https://user-images.githubusercontent.com/10366175/155381863-ce6f7e04-0746-4131-b7e3-4c85da562f69.png)

Küche Edison
![image](https://user-images.githubusercontent.com/10366175/155381905-1d7c5231-5b95-43b0-a166-4a9a254c947a.png)

For offerings you can use any CC images of coffee and beer

**Comment by anizeani** [comment]
what are CC images? 
can i just take an image from google of a beer & a coffee?

**Comment by brenzi** [comment]
creative commons (or public domain) no copyright restrictions
