### ISSUE TITLE
change naming of create_offering by create_product

### ISSUE THREAD

**Issue by anizeani** [encointer/encointer-node#179]
According to the scheme: https://github.com/encointer/pallets/blob/master/bazaar/README.md
we define a product to have all details (name, description etc) about the product and the offering to contain the product_cid with its price.
create_offering doesn't register an offering on the chain, but a product..
That's why I'd suggest to change the name of the method to reduce confusion

**Comment by brenzi** [comment]
I disagree. the chain registers an offering. it can be a *demand* or an *offer*
