### ISSUE TITLE
write voucher management tools

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-node#257]
we already have a script to generate voucher batches: `./client/voucher.py`

Community leaders should be able to scrape all remaining unused voucher funds after a specified time, i.e. 30 days

The mentioned script generates a `.secrets` file which contains one SURI per line in the format `//svinsdfvib/dfinbadcinad`

We should implement a script which:

1. calculates the account ss58 for each line
2. fetches the balance, with both principal and block components
3. calculate balance for today as well as number of days the account had no balance update
4. list all the above information: `ss58account, SURI, balance, days untouched`
5. allow user to specify a beneficiary account where all nonzero balances that havent been touched for > N days will be reaped to

**Comment by Malixxa** [comment]
In addition to 4., it would help to see the total Amount locked in vouchers.

**Comment by brenzi** [comment]
@Malixxa this will not be possible as there is no way (across multiple runs of voucher creation) to know if an account is a voucher or not

**Comment by brenzi** [comment]
replaced by #284
