### ISSUE TITLE
Client shall support `--atBlock` arg for various cmds.

### ISSUE THREAD

**Issue by clangenb** [encointer/encointer-node#282]
We can't query stuff for old ceremonies because the data has been purged from the chain after the reputation lifetime. Hence, we should allow the `atBlock` arg to get the state at a previous block, which solves that issue.

We might also want to add a command `getBlockForCeremonyStart`, which returns the block where the transition to that specific ceremony index  happened

**Comment by brenzi** [comment]
And for accounting we'll need dates too: get balance on Dec 31st EOD or end of each month

This is not trivial and may involve binary search with initial guessing based on blocktime.

**Comment by clangenb** [comment]
But here we could also just query an indexer first to get a block on a specific date. No need to manually implement this in the client here IMO.

**Comment by brenzi** [comment]
True. Although subscan doesn't support that kind of query AFAIK. Subquery?

**Comment by brenzi** [comment]
`--at` should take either hash or blocknumber if possible with reasonable effort
