### ISSUE TITLE
Enable release from branches

### ISSUE THREAD

**Issue by mosonyi** [encointer/encointer-node#295]
@echevrier would like to create a new release from her branch (the goal is to have a docker image)
The x.x.x pattern is reserved for the release from main.
@clangenb what pattern would you prefer for releasing from branch?

**Comment by clangenb** [comment]
I would like to to have it `x.x.x-for-tee`. Can we also rename the docker binaries to:

```
encointer-node-for-tee
enconter-client-for-tee
```

?

**Comment by mosonyi** [comment]
We don't rename the docker image just the version.
Example based on your request:  docker run -it encointer/encointer-node-notee:0.0.2-for-tee --help

**Comment by clangenb** [comment]
ok this is fine for me.

**Comment by clangenb** [comment]
Done
