### ISSUE TITLE
Clean up NYOTA on Gesell Testnet 

### ISSUE THREAD

**Issue by Malixxa** [encointer/encointer-node#318]
Please delete the following NYOTAs

kygcs5dYsjW: Nyota coin locations: 1
kygcs4CXfwf: NYOTA COIN locations: 1
kygcs5CPWah: Nyota COIN locations: 1
kygcs5wTtHM: Nyota COIN locations: 1
kygck5wTtHM: Nyota COIN locations: 1
kygck5dr3Wd: Nyota COIN locations: 1

And this one (was already active):

kygcs5dr3Wd: Nyota locations: 1

**Comment by brenzi** [comment]
done: 
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fgesell.encointer.org#/explorer/query/0x9b578654bcb34e4fb1f57d326ae9a87fa9e5cc5c9a6aa67e9331335000f65890
