### ISSUE TITLE
launch Zurich community

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-node#47]
Branding
* give it a name and a logo

Economics
* Define UBI nominal amount to be intuitive for CH

Community
* define set of bootstrappers for trusted setup
* public bootstrapping event

Businesses
* find shops who commit to accept the currency and advertise in Bazaar

**Comment by brenzi** [comment]
Branding
* give it a name and a logo

Economics
* Define UBI nominal amount to be intuitive for CH

Community
* define set of bootstrappers for trusted setup
* public bootstrapping event

Businesses
* find shops who commit to accept the currency and advertise in Bazaar

**Comment by Malixxa** [comment]
@brenzi this seems like an epic we should close.
