### ISSUE TITLE
benchmarking and stress-testing

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-node#51]
We'd like to know the limits of our implementation in order to quantify optimization success.

# setup
build and run latest notee node: 
```
git clone https://github.com/encointer/encointer-node.git
cd encointer-node
cargo build --release
./target/release/encointer-node-teeproxy --dev
```
then test our bot-community
```
apt install python3-geojson python3-pyproj
./bot-community.py init
./bot-community.py benchmark
```
Now it should grow a community with a hard-coded maximum size and number of meetup locations

# monitoring

You may want to spawn a prometheus instance to monitor node health during stresstests:
https://substrate.dev/docs/en/tutorials/visualize-node-metrics/

# automation

create a [docker setup](https://book.encointer.org/testnets.html#docker-demo) which can be easily reproduced on different machines!

The above only grows a single community. We'd like to parallelize this and scale stressing it horizontally. Python may not be the right tool because it is single-threaded. Maybe use a bashscrip to launch many bot-communities. You'll have to use `bot-community run` instead of `benchmark` and advance the phase from bash with client CLI `next-phase` command.

We want to stress the following dimensions and quantify results:
* as many tps as possible can be random token transfers
* more locations per community 
* more participants per community
* more token transfers per community
* more communities

parity has already developed tooling to set extrinsic weights based on benchmarking. This may be helpful:
* https://github.com/paritytech/substrate/issues/6168
* https://www.shawntabrizi.com/substrate-graph-benchmarks/docs/#/

So, in the end, a result of this work should also help us set weights for our extrinsics

**Comment by nomelc** [comment]
After initial setup and familiarizing myself with encointer-node I propose the following: 

Create a docker-compose with 

1. a container running encointer-node
  - [ ] Fix scripts/docker_run.sh
2. n replicas of a container that runs a containarized bot-community.py
  - [ ] Dockerize bot-community.py

optional
3. a container running monitoring with Grafana and Prometheus  
  - [ ] Dockerize monitoring setup

This should give a lot of flexibility for stress-testing horizontally and/or vertically.

**Comment by brenzi** [comment]
sounds reasonable. I suggest you use our docker image so you can easily port it to Cantillon as well, using SGX
```
scssubstratee/substratee_dev:1804-2.12-1.1.3-001
```

**Comment by nomelc** [comment]
I dockerized the stresstest and uploaded the image to dockerhub: https://hub.docker.com/r/nomelc/encointer-notee
