### ISSUE TITLE
upgrade Gesell to inverse attestation logic

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-node#71]
update all interacting components also:

- [x] wallet (master)
- [x] explorer [PR#42](https://github.com/encointer/explorer/pull/42) only merge upon gesell upgrade
- [x] bot communities (master)
- [x] tutorials (now python instead of bash

tagged repos:
- [x] encointer/pallets v0.6.0
- [x] encointer/encointer-node v0.4.0
- [x] encointer/explorer
- [x] encointer/book

**Comment by brenzi** [comment]
blocked by #83

**Comment by clangenb** [comment]
I think this can be closed, no? Gesell has been updated, but I don't know the state of the two open subtasks. If they are still pendent, we should open new issues.

**Comment by brenzi** [comment]
subtask open 
https://github.com/encointer/book/pull/3
