### ISSUE TITLE
make history data available

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-node#78]
includes:

encointer-indexer service:
* indexing of encointer chain, possibly based on [PolkaScan](https://github.com/polkascan/polkascan-os) (python) (or, alternatively [subscan](https://github.com/itering/subscan-essentials) (GO))

encointer/explorer additions:
* plot balance history (with applied demurrage and prediction/extrapolation)
* plot community history (total supply, ceremony statistics, history of parameters like demurrage rate, UBI, name, ....)

mobile app:
* tx history of own account

**Comment by Malixxa** [comment]
@clangenb if we implement this, what are we enhancing? System stability? Is this a must for improving the explorer? Could it facilitate growth?

**Comment by brenzi** [comment]
It helps community leaders to keep an overview. And it enables to provide transaction history in the app.
IMO not urgent, but sooner or later this will be a requirement for sure
