### ISSUE TITLE
common good parachain

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-node#79]

**Comment by clangenb** [comment]
@brenzi are you confident this issue should be in this repo?

**Comment by brenzi** [comment]
well, it's a cross-repo epic for zenhub. we can move it to parachain if you prefer

**Comment by clangenb** [comment]
Ah oh, I understand now. I thought it is a duplicate of 

* encointer/encointer-parachain/issues/27

But I see the difference now.
