### ISSUE TITLE
bot-community.py benchmark fails with inability to pay fees

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-node#83]
With `master` e72c585 I do 
```
../target/release/encointer-node-notee --dev --tmp --ws-port 9945 --enable-offchain-indexing true
```
and 
```
./bot-community.py --port 9945 init
./bot-community.py --port 9945 benchmark
```
the error I get
```
will grow population forever
cid is ERDQ3Kfc5oK97YrHwBaRugym2oYHW2id6v4TGcninYDy
phase is REGISTERING
number of known accounts: 20
****** money supply is 0.0
registering 20 participants
[2021-05-30T12:47:02Z ERROR ws::handler] WS Error <Custom(Extrinsic("extrinsic error code 1010: Invalid Transaction: Inability to pay some fees (e.g. account balance too low)"))>
```

**Comment by brenzi** [comment]
We have to ensure this works standalone but also in @nomelc's setup with a faucet service where we don't use `//Alice` because of nonce clashes

**Comment by clangenb** [comment]
This might be a systematic flaw. Benchmark tries to register all the accounts that exist in the keystore. I presume your keystore contains some accounts that have not been fauceted.

I suggest creating a separate keystore that is exclusively used to the benchmark script,  to prevent uninitialized accounts from interfering with the script.

**Comment by brenzi** [comment]
aaah, yes. I probably had the old keystore lying around.
Maybe 'init' should clean that? With prompting to be safe

**Comment by clangenb** [comment]
Yes, we can also do that.
