### ISSUE TITLE
set up polkascan indexer for testnet Gesell

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-node#85]
Try to scan Gesell with Polkascan and implement Encointer-specifc types

https://polkascan.io/

start here:
https://github.com/polkascan/polkascan-os

our api endpoint for gesell is:
wss://gesell.encointer.org

You might see trouble because of the outdated substrate version of Gesell. Then we can push the reset of Gesell to the new version.....

**Comment by brenzi** [comment]
@anizeani can you please ask polkascan for a new ETA on their new release?

**Comment by anizeani** [comment]
I'm on it

**Comment by brenzi** [comment]
please check again, frontend has been updated. hopefully the indexer too...

**Comment by anizeani** [comment]
i will

**Comment by brenzi** [comment]
We will be indexed by subscan soon. Closing this
