### ISSUE TITLE
set up powerful remote development machine

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-node#86]
# Requirements:
* 2-3 developers can build rust stuff remotely, quicker than on their laptops
* each dev will need > 50GB for their home

# Options

Digitalocean
* 32GB RAM, 200GB, 16 cores **320$/mt**

AWS E2
* 32GB RAM, 200GB, 16 cores **207$/mt**

OVH
* 32GB RAM, 320GB SSD, 8 vCores *87€/mt*
probably better to use 

c2-60 | 60&nbsp; GB | 16 | 400&nbsp; GB SSD | 1&nbsp; Gbit/s garantiert | maximal 4&nbsp; Gbit/s | 0,8103&nbsp;€ inkl. MwSt./Stunde
**532€/mt**

self-hosted (including SGX)
* Dell PowerEdge R340 Server CPU has to be Intel(R) Xeon(R) E-2276G CPU @ 3.80 GHz

# Setup
use devsgx* ansible script to bring up developer machines

**Comment by brenzi** [comment]
@NicJak 

Can you please benchmark your laptop the following way?

1. clone and `cargo build --release` paritytech/substrate
2. cargo clean
3. build again and measure time

**Comment by brenzi** [comment]
devsgx takes ~17min (wasn't the only active user though):

real    16m44.580s
user    165m25.981s
sys     5m41.379s

**Comment by brenzi** [comment]
i9 laptop with 32GB needed 18min

**Comment by NicJak** [comment]
ryzen 4750U, 32GB needed ~21min

I think the complexity of the setup might cost more than the extra 4 minutes...

**Comment by brenzi** [comment]
ok, perfect
