### ISSUE TITLE
[bazaar] implement python tool to register a few dummy shops and articles for bot communities

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-node#89]
1. extend https://github.com/encointer/encointer-node/tree/master/client/py_client to support new commands for bazaar #88 
2. implement dummy shop and article creation including ipfs storage. Either inside bot-communities.py or as its own tool

depends on #88

**Comment by clangenb** [comment]
I just realize that #93 might suffice completely to close this issue. I let @anizeani decide.

**Comment by anizeani** [comment]
> I just realize that #93 might suffice completely to close this issue. I let @anizeani decide.

I agree, especially now, that ipfs storage works locally & remotely, we can close this issue
