### ISSUE TITLE
[client] refactor rust-client

### ISSUE THREAD

**Issue by clangenb** [encointer/encointer-node#94]
The main.rs file is huge, and lacks overview. I propose several refactorings to simplify the client.

- [ ] Simply move all the api-client functions to a `api-wrapper` module.
- [ ] move some other functions to a `helpers` module
- [ ] Extract commands to a `cmd` module. See description below.

#### Extract commands
To get a good overview into the client's capabilities, it would be good if we can add commands with the following pattern:

```
...
.add_cmd(list_offerings_cmd())
```

This will keep the client main file short, and we see exactly which commands are supported.

**Comment by brenzi** [comment]
before we do that, I'd like to see a refactoring to structopt, as suggested in https://github.com/integritee-network/worker/issues/197

**Comment by clangenb** [comment]
I actually see it the other way around. I think the above refactoring is simpler because we only need to extract code. After the above steps, I would say we are ready to change to use struct_opt.

**Comment by clangenb** [comment]
I think this i no longer relevant. We will directly move to clap v3 at some point: #107
