### ISSUE TITLE
[cli] `new-community` should return cid in base58 format and not hex 

### ISSUE THREAD

**Issue by anizeani** [encointer/encointer-node#98]

**Comment by brenzi** [comment]
are you talking about the cli command  in the encointer-client crate? please be precise

**Comment by anizeani** [comment]
Yes, sry! I'm talking about the ecnointer-client

**Comment by brenzi** [comment]
wait for pallet/#54 where the display format will change

**Comment by clangenb** [comment]
The display format has been adjusted to print the cid like: https://github.com/encointer/pallets/blob/f701ef1a91f28a4a9f7daea61533d87c7f87f696/primitives/src/communities.rs#L75
